name: Gradle Build
description: Build Fabric mod with Gradle

runs:
  using: "composite"
  steps:
    - name: validate gradle wrapper
      uses: gradle/actions/wrapper-validation@v4
    - name: setup jdk
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'microsoft'
        cache: 'gradle'
    - name: make gradle wrapper executable
      shell: bash
      run: chmod +x ./gradlew
    - name: build
      shell: bash
      run: ./gradlew build
    - name: copy built jar to output dir
      shell: bash
      run: |
        mkdir -p mod-jar
        cp build/libs/*.jar mod-jar/
