branches:
  - "main"
tagFormat: "v${version}"
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/exec":
      - prepareCmd: "sed -i 's/^mod_version=.*/mod_version=${nextRelease.version}/' gradle.properties"
  - "@semantic-release/github"
