branches:
  - "main"
tagFormat: "v${version}"
plugins:
  - - "@semantic-release/commit-analyzer"
    - releaseRules:
        - type: fix
          release: patch
        - type: refactor
          release: patch
        - type: feat
          release: minor
        - breaking: true
          release: major
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/exec"
    - prepareCmd: sed -i s/^mod_version=.*/mod_version=${nextRelease.version}/ gradle.properties
  - - "@semantic-release/git"
    - assets:
        - gradle.properties
      message: "write release: ${nextRelease.version}"
  - "@semantic-release/github"
