name: build & validate
on:
  pull_request:

jobs:
  prepare-matrix:
    uses: ./.github/workflows/prepare-matrix.yml
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/gradle-build
      - uses: actions/upload-artifact@v4
        with:
          name: mod-jar-${{ github.sha }}
          path: mod-jar
  compatibility-tests:
    needs:
      - build
      - prepare-matrix
    runs-on: ubuntu-24.04
    strategy:
      matrix: ${{ fromJson(needs.prepare-matrix.outputs.matrix) }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: mod-jar-${{ github.sha }}
          path: mod-jar
      - uses: ./.github/actions/fabric-compatibility-check
        with:
          mc_version: ${{ matrix.mc_version }}
          loader_version: ${{ matrix.loader_version }}
          installer_version: ${{ matrix.installer_version }}
          additional_mod_urls: ${{ matrix.additional_mod_urls }}
