name: build & test
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/gradle-build
      - uses: actions/upload-artifact@v4
        with:
          name: mod-jar
          path: build/libs/*.jar
  compatibility-tests:
    needs: build
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        mc_version: [1.20.1, 1.21.11]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: mod-jar
      - uses: ./.github/actions/fabric-compatibility-check
        with:
          mc_version: ${{ matrix.mc_version }}
